FROM java:openjdk-8-jre
MAINTAINER Can Güney Aksakalli <can.gueney.aksakalli@fit.fraunhofer.de>, Jose Angel Carvajal Soto <carvajal@fit.fhg.de>

COPY . /usr/src/app/
WORKDIR /usr/src/app

RUN mvn clean install
WORKDIR gpl-artifacts
RUN mvn clean install

WORKDIR distributions/rest/IoTLearningAgent/target/

RUN ln -s /config/conf.cfg ./conf.cfg

VOLUME /config
ENTRYPOINT ["java", "-cp","./*", "org.springframework.boot.loader.PropertiesLauncher"]
EXPOSE 8319

#  docker run -v <<//D/workspaces/IoTAgents/gpl-artifacts/distributions/rest/IoTLearningAgent/docker-conf/>>:/config --add-host=broker:<<ip>> la-rest