language: java
jdk: openjdk10
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
services:
  - docker
jobs:
  include:
    - stage: "Maven Install (Unit & Integration Tests) & Docker Build & Push"
      name: "Building"
      script:
        - mvn clean -B install -B
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --force-rm -f gpl-artifacts/Dockerfile-local -t linksmart/dpa:experimental  .
        - docker push linksmart/dpa:experimental
        - docker build --force-rm -f Dockerfile-local -t linksmart/dpa:wso2-experimental  .
        - docker push linksmart/dpa:wso2-experimental
        - docker build --force-rm -f gpl-artifacts/Dockerfile-local --build-arg extensions=eu.linksmart.services.event.ceml.core.CEML -t linksmart/la:experimental .
        - docker push linksmart/la:experimental
        - docker build --force-rm -f Dockerfile-local --build-arg extensions=eu.linksmart.services.event.ceml.core.CEML -t linksmart/la:wso2-experimental  .
        - docker push linksmart/la:wso2-experimental
      install: true
    - stage: "System Tests"
      script:
        - git clone https://github.com/linksmart/dpa-tutorials.git
        - docker-compose -f dpa-tutorials/docker-compose.yml -f dpa-tutorials/docker-compose.tutorial.yml -f dpa-tutorials/testing/docker-compose-testing.yml up -d
        - cd dpa-tutorials/testing/
        - mvn -s ../../.travis.settings.xml test
      name: "DPA ST"
      git:
        depth: false
      install: true
    - script:
      - cd  test/la-basic-it/
      - docker-compose -f docker-compose.yml up -d
      - mvn -s ../../.travis.settings.xml test
      install: true
      name: "LA ST"
    - stage: "Deploy Artifacts"
      script: mvn -Dskip=test deploy -B #-Dlinksmart.commons.version=${LS_COMMONS_VERSION}-SNAPSHOT -Dskip=test -Dls.se.agents.version=${VERSION}-SNAPSHOT
      name: "Maven Deploy"
      install: true
    - script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull linksmart/dpa:experimental
        - docker pull linksmart/la:experimental
        - docker pull linksmart/dpa:wso2-experimental
        - docker pull linksmart/la:wso2-experimental
        - docker tag linksmart/dpa:experimental linksmart/dpa:snapshot
        - docker tag linksmart/la:experimental linksmart/la:snapshot
        - docker tag linksmart/dpa:wso2-experimental linksmart/dpa:wso2-snapshot
        - docker tag linksmart/la:wso2-experimental linksmart/la:wso2-snapshot
        - docker push linksmart/dpa:snapshot
        - docker push linksmart/la:snapshot
        - docker push linksmart/dpa:wso2-snapshot
        - docker push linksmart/la:wso2-snapshot
      git:
        depth: false
      install: true
      name: "Docker Push Images"
    - script: mvn javadoc:javadoc #-Dls.se.agents.version=${VERSION}-SNAPSHOT
      name: "Javadoc Deploy"
      install: true
    - script:
        - docker run --name broker -d eclipse-mosquitto:latest
        - docker run --name la --link broker -d linksmart/dpa:snapshot
#        - apt-get install curl
#        - apt-get install jq
        - export URL="http://dpa:8319/v2/api-docs?group=LinkSmart%20(R)%20IoT%20Learning%20Agent"
        - export FILE=api-docs.json
        - echo "" > ${FILE}
        - echo 'calling endpoint ${URL} storeging in ${FILE} ...';
        - curl -f --stderr err "${URL}" | jq '.' > ${FILE};
        - cat err;
        - until [ -s ${FILE} ]; do sleep 1; echo 'calling endpoint ${URL} storeging in ${FILE} ...'; curl -f --stderr err "${URL}" | jq '.' > ${FILE}; cat err;
        - done;
        - git add ${FILE}
        - "git commit -am '[skip travis] AUTOMATIC COMMIT: updating Open API'"
        - git push
 #       - ./.openAPI-extractor.sh
      name: "OpenAPI GIT Push"
      install: true
