FROM maven:3-jdk-10

# the folder where the apache code is located
VOLUME /apache-artifacts
# the folder where the LGPL code is located
VOLUME /gpl-artifacts

# building apache artifacts
WORKDIR /apache-artifacts
RUN mvn clean install

# moving to the jar location
WORKDIR distributions/IoTAgent/target/

# enabling environmental variables configuration
ENV env_var_enabled=true

# force the REST API port to the default one
ENV server_port=8319

# mounting configuration and extra dependencies volumes
VOLUME /config
VOLUME /dependencies

# starting the agent
ENTRYPOINT ["java", "--add-modules", "java.xml.bind","-cp","./*:/dependencies/*", "org.springframework.boot.loader.PropertiesLauncher"]



EXPOSE 8319
# NOTES:
#	RUN:
#  		docker run [options] <<image-name>> [command]
#   OPTIONS:
# 		Define volume for configuration file:
#			-v <</path/on/host/machine/conf>>:/config
# 		Define volume for configuration file:
#			-v <</path/on/host/machine/dep>>:/dependencies
# 		Disable/enable REST API:
#			-e api_rest_enabled=<false/true>
#		Define default broker
#			-e connection_broker_mqtt_hostname=<hostname>
#		Expose REST:
#			-p "8319:8319"
#   COMMAND:
#       Custom configuration file (volume should be defined):
#           /config/config.cfg
#
