FROM maven:3-jdk-8

COPY . /usr/src/app/
WORKDIR /usr/src/app

RUN mvn clean install
WORKDIR gpl-artifacts
RUN mvn clean install

WORKDIR distributions/rest/IoTLearningAgent/target/

ENV CLASSPATH .:./lib/ceml-1.4.0-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "iot.learning.rest.agent-1.4.0-SNAPSHOT.jar"]

RUN ln -s /config/conf.cfg ./conf.cfg

VOLUME /config
EXPOSE 8319