package eu.linksmart.api.event.datafusion.core;

/**
 *
 * This interface represent the DataFusionManagemant Core. The core is responsible of the intern logic of the DF manager.<p>
 * After the query is interpret and sent by the DFL-Interpret then DF-Core coordinate and take the necessary actions for the deployment of the query.
 *
 * @author José Ángel Carvajal Soto
 * @version     0.01
 * @since       0.01
 *
 * */

public interface DataFusionCore {

	/**
	 * Add a query to the manager.
	 *
	 * @param name of the query. This is how the query will be addressed. <p> Also name indicate where is going to be published when the query is triggered e.g. my.event.query the event will be publish in /my/event/query/
	 * @param query as Object. The type generated by the interpret is not get defined (temporal)
	 * @param topic where the query will be deployed
	 *
	 * @return <code>true</code> if the query was deployed successfully. <code>false</code> otherwise.
	 *
	 * */
	public boolean addQuery(String name, Object query, String[] topic);
	/// Temporal
	public boolean pauseQuery(String name);
	/// Temporal
	public boolean removeQuery(String name);
	/// Temporal
	public boolean startQuery(String name);

}
