//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.08 at 11:10:03 AM CEST 
//


package it.ismb.pertlab.pwal.event.format.linksmart.cnet.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventStatusCV.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventStatusCV">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Production"/>
 *     &lt;enumeration value="Test"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventStatusCV", namespace = "http://linksmart.org/Event/1.0")
@XmlEnum
public enum EventStatusCV {

    @XmlEnumValue("Production")
    PRODUCTION("Production"),
    @XmlEnumValue("Test")
    TEST("Test");
    private final String value;

    EventStatusCV(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventStatusCV fromValue(String v) {
        for (EventStatusCV c: EventStatusCV.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
