//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.08 at 11:10:03 AM CEST 
//


package it.ismb.pertlab.pwal.event.format.linksmart.cnet.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://linksmart.org/Event/1.0}EventMeta"/>
 *         &lt;element ref="{http://linksmart.org/Event/1.0}Source"/>
 *         &lt;element ref="{http://linksmart.org/Event/1.0}Content"/>
 *       &lt;/sequence>
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/1999/xhtml/datatypes/}SafeCURIEorCURIEorIRI" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *       &lt;attribute name="prefix" use="required" type="{http://linksmart.org/TypeLibrary/1.0}PrefixIRIDefinitionsType" />
 *       &lt;attribute name="eventStatus" use="required" type="{http://linksmart.org/Event/1.0}EventStatusCV" />
 *       &lt;attribute name="schemaVersion" use="required" type="{http://linksmart.org/TypeLibrary/1.0}SchemaVersionType" />
 *       &lt;attribute name="systemsID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventMeta",
    "source",
    "content"
})
@XmlRootElement(name = "Event", namespace = "http://linksmart.org/Event/1.0")
public class Event {

    @XmlElement(name = "EventMeta", namespace = "http://linksmart.org/Event/1.0", required = true)
    @JsonProperty(value = "EventMeta")
    protected EventMeta eventMeta;
    @XmlElement(name = "Source", namespace = "http://linksmart.org/Event/1.0", required = true)
    @JsonProperty(value = "Source")
    protected Source source;
    @XmlElement(name = "Content", namespace = "http://linksmart.org/Event/1.0", required = true)
    @JsonProperty(value = "Content")
    protected ContentType content;
    @XmlAttribute(name = "about", required = true)
    @JsonProperty(value = "About")
    protected String about;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "prefix", required = true)
    protected List<String> prefix;
    @XmlAttribute(name = "eventStatus", required = true)
    protected EventStatusCV eventStatus;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;
    @XmlAttribute(name = "systemsID", required = true)
    protected String systemsID;

    /**
     * Gets the value of the eventMeta property.
     * 
     * @return
     *     possible object is
     *     {@link EventMeta }
     *     
     */
    public EventMeta getEventMeta() {
        return eventMeta;
    }

    /**
     * Sets the value of the eventMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventMeta }
     *     
     */
    public void setEventMeta(EventMeta value) {
        this.eventMeta = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ContentType }
     *     
     */
    public ContentType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentType }
     *     
     */
    public void setContent(ContentType value) {
        this.content = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prefix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrefix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPrefix() {
        if (prefix == null) {
            prefix = new ArrayList<String>();
        }
        return this.prefix;
    }

    /**
     * Gets the value of the eventStatus property.
     * 
     * @return
     *     possible object is
     *     {@link EventStatusCV }
     *     
     */
    public EventStatusCV getEventStatus() {
        return eventStatus;
    }

    /**
     * Sets the value of the eventStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventStatusCV }
     *     
     */
    public void setEventStatus(EventStatusCV value) {
        this.eventStatus = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the systemsID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemsID() {
        return systemsID;
    }

    /**
     * Sets the value of the systemsID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemsID(String value) {
        this.systemsID = value;
    }

}
