//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.08 at 11:10:03 AM CEST 
//


package it.ismb.pertlab.pwal.event.format.linksmart.cnet.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://linksmart.org/IoTEntity/1.0}Name" minOccurs="0"/>
 *         &lt;element ref="{http://linksmart.org/IoTEntity/1.0}Description" minOccurs="0"/>
 *         &lt;element ref="{http://linksmart.org/IoTEntity/1.0}UnitOfMeasurement" minOccurs="0"/>
 *         &lt;element ref="{http://linksmart.org/IoTEntity/1.0}Meta" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://linksmart.org/IoTEntity/1.0}IoTStateObservation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;any processContents='skip' namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}base"/>
 *       &lt;attribute name="prefix" type="{http://linksmart.org/TypeLibrary/1.0}PrefixIRIDefinitionsType" />
 *       &lt;attribute name="about" use="required" type="{http://www.w3.org/1999/xhtml/datatypes/}SafeCURIEorCURIEorIRI" />
 *       &lt;attribute name="typeof" use="required" type="{http://www.w3.org/1999/xhtml/datatypes/}TERMorCURIEorAbsIRIs" />
 *       &lt;attribute name="datatype" type="{http://www.w3.org/1999/xhtml/datatypes/}TERMorCURIEorAbsIRI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "description",
    "unitOfMeasurement",
    "meta",
    "ioTStateObservation",
    "any"
})
@XmlRootElement(name = "IoTProperty")
public class IoTProperty {

    @XmlElement(name = "Name")
    @JsonProperty(value = "Name")
    protected String name;
    @XmlElement(name = "Description")
    @JsonProperty(value = "Description")
    protected String description;
    @XmlElement(name = "UnitOfMeasurement")
    @JsonProperty(value = "UnitOfMeasurement")
    protected TypedStringType unitOfMeasurement;
    @XmlElement(name = "Meta")
    @JsonProperty(value = "Meta")
    protected List<MetaType> meta;
    @XmlElement(name = "IoTStateObservation")
    @JsonProperty(value = "IoTStateObservation")
    protected List<IoTStateObservation> ioTStateObservation;
    @XmlAnyElement
    protected List<Element> any;
    @XmlAttribute(name = "base", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlSchemaType(name = "anyURI")
    protected String base;
    @XmlAttribute(name = "prefix")
    @JsonProperty(value = "Prefix")
    protected List<String> prefix;
    @XmlAttribute(name = "about", required = true)
    @JsonProperty(value = "About")
    protected String about;
    @XmlAttribute(name = "typeof", required = true)
    @JsonProperty(value = "TypeOf")
    protected List<String> typeof;
    @XmlAttribute(name = "datatype")
    @JsonProperty(value = "DataType")
    protected String datatype;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the unitOfMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link TypedStringType }
     *     
     */
    public TypedStringType getUnitOfMeasurement() {
        return unitOfMeasurement;
    }

    /**
     * Sets the value of the unitOfMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypedStringType }
     *     
     */
    public void setUnitOfMeasurement(TypedStringType value) {
        this.unitOfMeasurement = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the meta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaType }
     * 
     * 
     */
    public List<MetaType> getMeta() {
        if (meta == null) {
            meta = new ArrayList<MetaType>();
        }
        return this.meta;
    }

    /**
     * Gets the value of the ioTStateObservation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ioTStateObservation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIoTStateObservation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IoTStateObservation }
     * 
     * 
     */
    public List<IoTStateObservation> getIoTStateObservation() {
        if (ioTStateObservation == null) {
            ioTStateObservation = new ArrayList<IoTStateObservation>();
        }
        return this.ioTStateObservation;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prefix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrefix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPrefix() {
        if (prefix == null) {
            prefix = new ArrayList<String>();
        }
        return this.prefix;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the typeof property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeof property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeof().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTypeof() {
        if (typeof == null) {
            typeof = new ArrayList<String>();
        }
        return this.typeof;
    }

    /**
     * Gets the value of the datatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * Sets the value of the datatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatatype(String value) {
        this.datatype = value;
    }

}
