version: '2'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  agent:
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - ./config:/config:ro
#      - ./dependencies:/dependencies:ro
    depends_on:
      - mqtt-broker
    links:
      - mqtt-broker
    environment:
      - connection_broker_mqtt_hostname=mqtt-broker
    ports:
      - "8319:8319"
