//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 06:23:23 PM CEST 
//


package it.ismb.pertlab.pwal.etsi_m2m_manager.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Application complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Application">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}expirationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}searchStrings" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}announceTo" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}aPoC" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}aPoCPaths" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}locRequestor" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}referencePoint" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}containersReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}groupsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}notificationChannelsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="appId" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Application", propOrder = {
    "expirationTime",
    "accessRightID",
    "searchStrings",
    "creationTime",
    "lastModifiedTime",
    "announceTo",
    "aPoC",
    "aPoCPaths",
    "locRequestor",
    "referencePoint",
    "containersReference",
    "groupsReference",
    "accessRightsReference",
    "subscriptionsReference",
    "notificationChannelsReference"
})
public class Application {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expirationTime;
    @XmlSchemaType(name = "anyURI")
    protected String accessRightID;
    protected SearchStrings searchStrings;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedTime;
    protected AnnounceTo announceTo;
    @XmlSchemaType(name = "anyURI")
    protected String aPoC;
    protected APoCPaths aPoCPaths;
    protected Object locRequestor;
    protected ReferencePoint referencePoint;
    @XmlSchemaType(name = "anyURI")
    protected String containersReference;
    @XmlSchemaType(name = "anyURI")
    protected String groupsReference;
    @XmlSchemaType(name = "anyURI")
    protected String accessRightsReference;
    @XmlSchemaType(name = "anyURI")
    protected String subscriptionsReference;
    @XmlSchemaType(name = "anyURI")
    protected String notificationChannelsReference;
    @XmlAttribute(name = "appId")
    @XmlSchemaType(name = "anyURI")
    protected String appId;

    /**
     * Gets the value of the expirationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationTime() {
        return expirationTime;
    }

    /**
     * Sets the value of the expirationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationTime(XMLGregorianCalendar value) {
        this.expirationTime = value;
    }

    /**
     * Gets the value of the accessRightID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessRightID() {
        return accessRightID;
    }

    /**
     * Sets the value of the accessRightID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessRightID(String value) {
        this.accessRightID = value;
    }

    /**
     * Gets the value of the searchStrings property.
     * 
     * @return
     *     possible object is
     *     {@link SearchStrings }
     *     
     */
    public SearchStrings getSearchStrings() {
        return searchStrings;
    }

    /**
     * Sets the value of the searchStrings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchStrings }
     *     
     */
    public void setSearchStrings(SearchStrings value) {
        this.searchStrings = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedTime(XMLGregorianCalendar value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the announceTo property.
     * 
     * @return
     *     possible object is
     *     {@link AnnounceTo }
     *     
     */
    public AnnounceTo getAnnounceTo() {
        return announceTo;
    }

    /**
     * Sets the value of the announceTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnounceTo }
     *     
     */
    public void setAnnounceTo(AnnounceTo value) {
        this.announceTo = value;
    }

    /**
     * Gets the value of the aPoC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPoC() {
        return aPoC;
    }

    /**
     * Sets the value of the aPoC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPoC(String value) {
        this.aPoC = value;
    }

    /**
     * Gets the value of the aPoCPaths property.
     * 
     * @return
     *     possible object is
     *     {@link APoCPaths }
     *     
     */
    public APoCPaths getAPoCPaths() {
        return aPoCPaths;
    }

    /**
     * Sets the value of the aPoCPaths property.
     * 
     * @param value
     *     allowed object is
     *     {@link APoCPaths }
     *     
     */
    public void setAPoCPaths(APoCPaths value) {
        this.aPoCPaths = value;
    }

    /**
     * Gets the value of the locRequestor property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLocRequestor() {
        return locRequestor;
    }

    /**
     * Sets the value of the locRequestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLocRequestor(Object value) {
        this.locRequestor = value;
    }

    /**
     * Gets the value of the referencePoint property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencePoint }
     *     
     */
    public ReferencePoint getReferencePoint() {
        return referencePoint;
    }

    /**
     * Sets the value of the referencePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencePoint }
     *     
     */
    public void setReferencePoint(ReferencePoint value) {
        this.referencePoint = value;
    }

    /**
     * Gets the value of the containersReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainersReference() {
        return containersReference;
    }

    /**
     * Sets the value of the containersReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainersReference(String value) {
        this.containersReference = value;
    }

    /**
     * Gets the value of the groupsReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupsReference() {
        return groupsReference;
    }

    /**
     * Sets the value of the groupsReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupsReference(String value) {
        this.groupsReference = value;
    }

    /**
     * Gets the value of the accessRightsReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessRightsReference() {
        return accessRightsReference;
    }

    /**
     * Sets the value of the accessRightsReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessRightsReference(String value) {
        this.accessRightsReference = value;
    }

    /**
     * Gets the value of the subscriptionsReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionsReference() {
        return subscriptionsReference;
    }

    /**
     * Sets the value of the subscriptionsReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

    /**
     * Gets the value of the notificationChannelsReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationChannelsReference() {
        return notificationChannelsReference;
    }

    /**
     * Sets the value of the notificationChannelsReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationChannelsReference(String value) {
        this.notificationChannelsReference = value;
    }

    /**
     * Gets the value of the appId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppId() {
        return appId;
    }

    /**
     * Sets the value of the appId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppId(String value) {
        this.appId = value;
    }

}
