//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 04:50:17 PM CEST 
//


package it.ismb.pertlab.pwal.etsi_m2m_manager.model.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentInstancesFilterCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentInstancesFilterCriteriaType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://uri.etsi.org/m2m}FilterCriteriaType">
 *       &lt;sequence>
 *         &lt;element name="sizeFrom" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="sizeUntil" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="metaDataOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentInstancesFilterCriteriaType", propOrder = {
    "sizeFrom",
    "sizeUntil",
    "contentType",
    "metaDataOnly"
})
public class ContentInstancesFilterCriteriaType
    extends FilterCriteriaType
{

    @XmlElement(namespace = "")
    protected Long sizeFrom;
    @XmlElement(namespace = "")
    protected Long sizeUntil;
    @XmlElement(namespace = "")
    protected List<String> contentType;
    @XmlElement(namespace = "")
    protected Boolean metaDataOnly;

    /**
     * Gets the value of the sizeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSizeFrom() {
        return sizeFrom;
    }

    /**
     * Sets the value of the sizeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSizeFrom(Long value) {
        this.sizeFrom = value;
    }

    /**
     * Gets the value of the sizeUntil property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSizeUntil() {
        return sizeUntil;
    }

    /**
     * Sets the value of the sizeUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSizeUntil(Long value) {
        this.sizeUntil = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContentType() {
        if (contentType == null) {
            contentType = new ArrayList<String>();
        }
        return this.contentType;
    }

    /**
     * Gets the value of the metaDataOnly property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMetaDataOnly() {
        return metaDataOnly;
    }

    /**
     * Sets the value of the metaDataOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMetaDataOnly(Boolean value) {
        this.metaDataOnly = value;
    }

}
