//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 10:18:25 AM CEST 
//


package it.ismb.pertlab.pwal.etsi_m2m_manager.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LongPollingChannelData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LongPollingChannelData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://uri.etsi.org/m2m}ChannelData">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}longPollingURI"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LongPollingChannelData", propOrder = {
    "longPollingURI"
})
public class LongPollingChannelData
    extends ChannelData
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String longPollingURI;

    /**
     * Gets the value of the longPollingURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongPollingURI() {
        return longPollingURI;
    }

    /**
     * Sets the value of the longPollingURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongPollingURI(String value) {
        this.longPollingURI = value;
    }

}
