//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 06:20:56 PM CEST 
//


package it.ismb.pertlab.pwal.etsi_m2m_manager.model.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PermissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PermissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}permissionFlags"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}permissionHolders"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://uri.etsi.org/m2m}id"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PermissionType", propOrder = {
    "permissionFlags",
    "permissionHolders"
})
public class PermissionType {

    @XmlElement(required = true)
    protected PermissionFlagListType permissionFlags;
    @XmlElement(required = true)
    protected PermissionHolderType permissionHolders;
    @XmlAttribute(name = "id", namespace = "http://uri.etsi.org/m2m")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String id;

    /**
     * Gets the value of the permissionFlags property.
     * 
     * @return
     *     possible object is
     *     {@link PermissionFlagListType }
     *     
     */
    public PermissionFlagListType getPermissionFlags() {
        return permissionFlags;
    }

    /**
     * Sets the value of the permissionFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissionFlagListType }
     *     
     */
    public void setPermissionFlags(PermissionFlagListType value) {
        this.permissionFlags = value;
    }

    /**
     * Gets the value of the permissionHolders property.
     * 
     * @return
     *     possible object is
     *     {@link PermissionHolderType }
     *     
     */
    public PermissionHolderType getPermissionHolders() {
        return permissionHolders;
    }

    /**
     * Sets the value of the permissionHolders property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermissionHolderType }
     *     
     */
    public void setPermissionHolders(PermissionHolderType value) {
        this.permissionHolders = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
