//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.30 at 04:50:17 PM CEST 
//


package it.ismb.pertlab.pwal.estsi_m2m_manager_v2.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ContentInstances complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentInstances">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}currentNrOfInstances" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}currentByteSize" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}contentInstanceCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}latest" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}oldest" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentInstances", propOrder = {
    "creationTime",
    "lastModifiedTime",
    "currentNrOfInstances",
    "currentByteSize",
    "contentInstanceCollection",
    "latest",
    "oldest",
    "subscriptionsReference"
})
public class ContentInstances {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedTime;
    protected Long currentNrOfInstances;
    protected Long currentByteSize;
    protected ContentInstanceCollection contentInstanceCollection;
    protected ReferenceToNamedResource latest;
    protected ReferenceToNamedResource oldest;
    @XmlSchemaType(name = "anyURI")
    protected String subscriptionsReference;

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedTime(XMLGregorianCalendar value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the currentNrOfInstances property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCurrentNrOfInstances() {
        return currentNrOfInstances;
    }

    /**
     * Sets the value of the currentNrOfInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCurrentNrOfInstances(Long value) {
        this.currentNrOfInstances = value;
    }

    /**
     * Gets the value of the currentByteSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCurrentByteSize() {
        return currentByteSize;
    }

    /**
     * Sets the value of the currentByteSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCurrentByteSize(Long value) {
        this.currentByteSize = value;
    }

    /**
     * Gets the value of the contentInstanceCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ContentInstanceCollection }
     *     
     */
    public ContentInstanceCollection getContentInstanceCollection() {
        return contentInstanceCollection;
    }

    /**
     * Sets the value of the contentInstanceCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentInstanceCollection }
     *     
     */
    public void setContentInstanceCollection(ContentInstanceCollection value) {
        this.contentInstanceCollection = value;
    }

    /**
     * Gets the value of the latest property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceToNamedResource }
     *     
     */
    public ReferenceToNamedResource getLatest() {
        return latest;
    }

    /**
     * Sets the value of the latest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceToNamedResource }
     *     
     */
    public void setLatest(ReferenceToNamedResource value) {
        this.latest = value;
    }

    /**
     * Gets the value of the oldest property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceToNamedResource }
     *     
     */
    public ReferenceToNamedResource getOldest() {
        return oldest;
    }

    /**
     * Sets the value of the oldest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceToNamedResource }
     *     
     */
    public void setOldest(ReferenceToNamedResource value) {
        this.oldest = value;
    }

    /**
     * Gets the value of the subscriptionsReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriptionsReference() {
        return subscriptionsReference;
    }

    /**
     * Sets the value of the subscriptionsReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

}
