FROM debian:jessie
MAINTAINER Can Güney Aksakalli <can.gueney.aksakalli@fit.fraunhofer.de>

LABEL description="A simple MQTT broker container running with default configuration"

RUN apt-get update && apt-get install -y mosquitto

EXPOSE 1883 8883

CMD ["mosquitto"]
