FROM java:openjdk-8-jre
MAINTAINER Can Güney Aksakalli <can.gueney.aksakalli@fit.fraunhofer.de>, Jose Angel Carvajal Soto <carvajal@fit.fhg.de>

COPY . /usr/src/app/
WORKDIR /usr/src/app

RUN mvn clean install
WORKDIR gpl-artifacts
RUN mvn clean install

WORKDIR gpl-artifacts/distributions/mqtt/IoTDataProcessingAgent/target

RUN ln -s /config/conf.cfg ./conf.cfg

VOLUME /config
ENTRYPOINT ["java", "-cp","./*", "eu.linksmart.services.Application"]
EXPOSE 8319
