//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.16 at 10:22:49 AM CEST 
//


package it.ismb.pertlab.pwal.datapusher.cnet.datamodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.ismb.pertlab.pwal.datamanager.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PhenomenonTime_QNAME = new QName("http://linksmart.org/IoTEntity/1.0", "PhenomenonTime");
    private final static QName _Description_QNAME = new QName("http://linksmart.org/IoTEntity/1.0", "Description");
    private final static QName _Value_QNAME = new QName("http://linksmart.org/IoTEntity/1.0", "Value");
    private final static QName _UnitOfMeasurement_QNAME = new QName("http://linksmart.org/IoTEntity/1.0", "UnitOfMeasurement");
    private final static QName _Name_QNAME = new QName("http://linksmart.org/IoTEntity/1.0", "Name");
    private final static QName _ResultTime_QNAME = new QName("http://linksmart.org/IoTEntity/1.0", "ResultTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.ismb.pertlab.pwal.datamanager.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IoTProperty }
     * 
     */
    public IoTProperty createIoTProperty() {
        return new IoTProperty();
    }

    /**
     * Create an instance of {@link TypedStringType }
     * 
     */
    public TypedStringType createTypedStringType() {
        return new TypedStringType();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link IoTStateObservation }
     * 
     */
    public IoTStateObservation createIoTStateObservation() {
        return new IoTStateObservation();
    }

    /**
     * Create an instance of {@link IoTEntity }
     * 
     */
    public IoTEntity createIoTEntity() {
        return new IoTEntity();
    }

    /**
     * Create an instance of {@link ArrayOfIoTEntity }
     * 
     */
    public ArrayOfIoTEntity createArrayOfIoTEntity() {
        return new ArrayOfIoTEntity();
    }

    /**
     * Create an instance of {@link ArrayOfIoTStateObservation }
     * 
     */
    public ArrayOfIoTStateObservation createArrayOfIoTStateObservation() {
        return new ArrayOfIoTStateObservation();
    }

    /**
     * Create an instance of {@link ArrayOfIoTProperty }
     * 
     */
    public ArrayOfIoTProperty createArrayOfIoTProperty() {
        return new ArrayOfIoTProperty();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://linksmart.org/IoTEntity/1.0", name = "PhenomenonTime")
    public JAXBElement<XMLGregorianCalendar> createPhenomenonTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PhenomenonTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://linksmart.org/IoTEntity/1.0", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://linksmart.org/IoTEntity/1.0", name = "Value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://linksmart.org/IoTEntity/1.0", name = "UnitOfMeasurement")
    public JAXBElement<TypedStringType> createUnitOfMeasurement(TypedStringType value) {
        return new JAXBElement<TypedStringType>(_UnitOfMeasurement_QNAME, TypedStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://linksmart.org/IoTEntity/1.0", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://linksmart.org/IoTEntity/1.0", name = "ResultTime")
    public JAXBElement<XMLGregorianCalendar> createResultTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ResultTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
