//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.16 at 10:22:49 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://linksmart.org/IoTEntity/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.ismb.pertlab.pwal.datapusher.cnet.datamodel;
